//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.ControleDispositivo.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DISPCONTROLEntities : DbContext
    {
        public DISPCONTROLEntities()
            : base("name=DISPCONTROLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_AGENCIA> TB_AGENCIA { get; set; }
        public virtual DbSet<TB_DISPOSITIVO> TB_DISPOSITIVO { get; set; }
        public virtual DbSet<TB_FABRICANTE_DISPOSITIVO> TB_FABRICANTE_DISPOSITIVO { get; set; }
        public virtual DbSet<TB_FIRMWARE> TB_FIRMWARE { get; set; }
        public virtual DbSet<TB_MODELO_DISPOSITIVO> TB_MODELO_DISPOSITIVO { get; set; }
        public virtual DbSet<TB_OPERADORA> TB_OPERADORA { get; set; }
        public virtual DbSet<TB_SIMCARD> TB_SIMCARD { get; set; }
        public virtual DbSet<TB_SITUACAO> TB_SITUACAO { get; set; }
        public virtual DbSet<TB_UNIDADE> TB_UNIDADE { get; set; }
    }
}
