//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.ControleDispositivo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AGENCIA
    {
        public TB_AGENCIA()
        {
            this.TB_DISPOSITIVO = new HashSet<TB_DISPOSITIVO>();
            this.TB_SIMCARD = new HashSet<TB_SIMCARD>();
            this.TB_UNIDADE = new HashSet<TB_UNIDADE>();
        }
    
        public int CODIGO_AGENCIA { get; set; }
        public string NM_AGENCIA { get; set; }
    
        public virtual ICollection<TB_DISPOSITIVO> TB_DISPOSITIVO { get; set; }
        public virtual ICollection<TB_SIMCARD> TB_SIMCARD { get; set; }
        public virtual ICollection<TB_UNIDADE> TB_UNIDADE { get; set; }
    }
}
