//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.ControleDispositivo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DISPOSITIVO
    {
        public int CODIGO_DISPOSITIVO { get; set; }
        public int CODIGO_FABRICANTE { get; set; }
        public int CODIGO_MODELO { get; set; }
        public int CODIGO_FIRMWARE { get; set; }
        public string NR_IMEI { get; set; }
        public Nullable<int> CODIGO_SIMCARD_PRIMARIO { get; set; }
        public Nullable<int> CODIGO_SIMCARD_SECUNDARIO { get; set; }
        public int CODIGO_SITUACAO { get; set; }
        public int CODIGO_UNIDADE { get; set; }
        public int CODIGO_AGENCIA { get; set; }
    
        public virtual TB_FABRICANTE_DISPOSITIVO TB_FABRICANTE_DISPOSITIVO { get; set; }
        public virtual TB_FIRMWARE TB_FIRMWARE { get; set; }
        public virtual TB_MODELO_DISPOSITIVO TB_MODELO_DISPOSITIVO { get; set; }
        public virtual TB_SIMCARD TB_SIMCARD { get; set; }
        public virtual TB_SIMCARD TB_SIMCARD1 { get; set; }
        public virtual TB_SITUACAO TB_SITUACAO { get; set; }
        public virtual TB_UNIDADE TB_UNIDADE { get; set; }
        public virtual TB_AGENCIA TB_AGENCIA { get; set; }
    }
}
