//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.ControleDispositivo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MODELO_DISPOSITIVO
    {
        public TB_MODELO_DISPOSITIVO()
        {
            this.TB_DISPOSITIVO = new HashSet<TB_DISPOSITIVO>();
        }
    
        public int CODIGO_MODELO { get; set; }
        public int CODIGO_FABRICANTE_DISPOSITIVO { get; set; }
        public string NM_MODELO_DISPOSITIVO { get; set; }
        public int NR_SIMCARDS { get; set; }
    
        public virtual ICollection<TB_DISPOSITIVO> TB_DISPOSITIVO { get; set; }
        public virtual TB_FABRICANTE_DISPOSITIVO TB_FABRICANTE_DISPOSITIVO { get; set; }
    }
}
