//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.ControleDispositivo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OPERADORA
    {
        public TB_OPERADORA()
        {
            this.TB_SIMCARD = new HashSet<TB_SIMCARD>();
        }
    
        public int CODIGO_OPERADORA { get; set; }
        public string NM_OPERADORA { get; set; }
    
        public virtual ICollection<TB_SIMCARD> TB_SIMCARD { get; set; }
    }
}
