//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.ControleDispositivo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SIMCARD
    {
        public TB_SIMCARD()
        {
            this.TB_DISPOSITIVO = new HashSet<TB_DISPOSITIVO>();
            this.TB_DISPOSITIVO1 = new HashSet<TB_DISPOSITIVO>();
        }
    
        public int CODIGO_SIMCARD { get; set; }
        public int CODIGO_OPERADORA { get; set; }
        public string NR_SIMCARD { get; set; }
        public int CODIGO_AGENCIA { get; set; }
        public string NR_CCID { get; set; }
    
        public virtual ICollection<TB_DISPOSITIVO> TB_DISPOSITIVO { get; set; }
        public virtual ICollection<TB_DISPOSITIVO> TB_DISPOSITIVO1 { get; set; }
        public virtual TB_OPERADORA TB_OPERADORA { get; set; }
        public virtual TB_AGENCIA TB_AGENCIA { get; set; }
    }
}
