//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.ControleDispositivo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SITUACAO
    {
        public TB_SITUACAO()
        {
            this.TB_DISPOSITIVO = new HashSet<TB_DISPOSITIVO>();
        }
    
        public int CODIGO_SITUACAO { get; set; }
        public string NM_SITUACAO { get; set; }
    
        public virtual ICollection<TB_DISPOSITIVO> TB_DISPOSITIVO { get; set; }
    }
}
